# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
    fileSystems = [ "/" ];
  };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/7aa77ad9-f61e-480b-844d-28dfa9ea5108";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      options = [ "subvol=@nixos_root" "compress=zstd" "noatime"  ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      options = [ "subvol=@nixos_home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      options = [ "subvol=@nixos_nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      options = [ "subvol=@nixos_nixos_config" "compress=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=@nixos_persist" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=@nixos_log" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F1B4-8B26";
      fsType = "vfat";
      options = [ "dmask=0077" "fmask=0077"  ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/8a9436b9-2305-42de-9dc1-d8c6bd20f447";
      fsType = "btrfs";
      options = [ "subvol=@nixos_swap" "noatime"  ];
    };


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
